import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Cabin } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import { QueryProvider } from "@/providers/react-query";

const inter = Inter({ subsets: ["latin"] });
const cabin = Cabin({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <QueryProvider>
          <Navbar />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
